image: jpetazzo/dind:latest
env:
  - LOG=file
  - BUNDLE_FROZEN=1
  - BUNDLE_PATH=/usr/local/bundle
  - BUNDLE_BIN=/usr/local/bundle/bin
  - BUNDLE_APP_CONFIG=/usr/local/bundle
script:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) --retry 5
  - wrapdocker bundle exec rake
  - start-stop-daemon --stop --pidfile "/var/run/docker.pid"
cache:
  - /usr/local/bundle
